### ISSUE TITLE
Small text on graphs

### ISSUE THREAD

**Issue by colfin22** [neoground/neowx#11]
This is probably not an issue but more of a configuration problem. The text on my graphs is not legible.

![Screenshot-20191125163034-1267x621](https://user-images.githubusercontent.com/1169559/69559182-5fd27200-0fa1-11ea-8ede-2a69c0dfcbfc.png)

**Comment by Maginos2210** [comment]
I recommend you to have a look at your skin.conf file (located in /etc/weewx/skins/NAME_OF_YOUR_SKIN). Open the file with:
`sudo nano /etc/weewx/skins/neowx/skin.conf`

Search for font_size by ctrl + w and type in font_size. Then you should get results like top_label_font_size = xy, unit_label_font_size = xyz, and also for bottom, axis and rose label. Change that size and make sure that you have installed the font you want to use, for example DroidSans. Then the font sizes of the graphs should change.
