### ISSUE TITLE
Remove unused panels

### ISSUE THREAD

**Issue by stalkerGH** [neoground/neowx#18]
First of all, thank you for beautiful Weewx theme. I'm testing my first DIY station and trying to customize NeoWX to fit my needs.

Because my setup is very basic (BME280 sensor) and I got only temperature, humidity and pressure data, I don't need all of the possible panels. I'd like to remove wind, rain etc., leaving only T, H, P and HI ones. In the futore, when my setup grow with other sensors, I'd like to come back with some panels.

How could I remove unused panels then? I've noticed such hook for UV index:

#if $day.UV.has_data

Could I use it for other parameters too or should I manually comment/remove the code in .tmpl files?

**Comment by Maginos2210** [comment]
@stalkerGH What you could do to get rid of the panels, you don't need:

-go to the folder /etc/weewx/skins/neowx and create a backup of the index.html.tmpl by executing "cp index.html.tmpl index.html.tmpl.old". In case you screw up the template, you can delete it and restore your old configuration with "cp index.html.tmpl.old index.html.tmpl".

-open the template with an editor, e. g. nano index.html.tmpl

-scroll down to the sections, where the graphs are defined. You know them by this lines:

<div class="col col-4 crd">

                        <h4><i class="wi wi-umbrella"></i> $Extras.Translation.rain</h4>
                        <div class="crd-content">
                            <span class="weatherdata">$day.rain.sum</span>
                            <table class="meta">
                                <tr>
                                    <td>$Extras.Translation.rain_rate:</td>
                                    <td>$current.rainRate</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>$Extras.Translation.high $Extras.Translation.rain_rate:</td>
                                    <td>$day.rainRate.max</td>
                                    <td>($day.rainRate.maxtime.format("%H:%M"))</td>
                                </tr>
                            </table>
                        </div>

                    </div>

This section for example is for the rain graph. I personally would comment out the sections you don't need by changing the section above into this:



As you can see, I added a  at the end of the last line. Do this with every graph you don't want to see and you're done.

**Comment by stalkerGH** [comment]
:+1:  Thank you very much!
