### ISSUE TITLE
Missing humidity graph

### ISSUE THREAD

**Issue by HyperDevil** [neoground/neowx#19]
Hi,

New installation of weewx, used the neowx skin with default settings.

```
        [[[dayhumidity]]]
            [[[[outHumidity]]]]

```

But no graph pops up on the main page.
The data is visible in the text on the top of the page.
How to get the humidity graph to show?

**Comment by neoground** [comment]
You added these sub-sections to the ImageGenerator section. This will only trigger the image generation, so there is a `dayhumidity.png` file.
To display it in the front page, edit the `index.html.tmpl` file.

After line 476 (end if) add:

```
<div class="row gutters row-gutters">
            <div class="col col-6 crd graph-crd">
                <h4>$Extras.Translation.out_humidity</h4>
                <a data-fancybox="gallery" href="dayhumidity.png"><img src="dayhumidity.png" alt="$Extras.Translation.out_humidity"></a>
            </div>
        </div>
```

This will show the graph image and make it clickable like the other ones.

Btw: recently I created a newer skin with many improvements, including all available sensors and interactive graphs. More information: https://neoground.com/projects/neowx-material
