### ISSUE TITLE
Change to km/h

### ISSUE THREAD

**Issue by colfin22** [neoground/neowx#23]
This is a support question rather than an issue, I hope you don't mind. I'd like to change the default wind speed from m/s to km/h but leave the rain measurements in mm. How do I go about this in this skin?

**Comment by neoground** [comment]
In your weewx.conf configuration you find a [StdReport] section where all html reports are defined.

This can also be extended so you can define your own units for each type and each report.

See the customization docs: http://www.weewx.com/docs/customizing.htm#how_to_change_units
