### ISSUE TITLE
Graphs only have lines from skin install time forward

### ISSUE THREAD

**Issue by MadderPad** [neoground/neowx#3]
![img_0123](https://user-images.githubusercontent.com/19325302/50572743-fe207c80-0dbe-11e9-9fae-5df0873c58d5.PNG)

So I started running Weewx approx 24 hours before I installed neowx - as you can see above for readings before neowx was installed I only have the points on the graph no line. I'm not sure if this is an issue in neowx or in Weewx? 

(BTW I initially thought the readings prior to installing neowx where gone, because by default the points have no marker.)

**Comment by neoground** [comment]
The image generation settings are found in the `[ImageGenerator]` section in the `skin.conf`. By default neowx has lines but no points and should look like in the screenshots.
Please check your `weewx.conf` which shouldn't contain any graph configuration. I guess the default image generation are just points and the neowx configuration adds the lines. This would explain this behaviour and also why your graphs show points as well. 
Normally weewx re-generates all graphs based on the latest settings if they change, so it seems to be a weewx issue. But I will check this problem and how weewx behaves on changed graph settings.

**Comment by MadderPad** [comment]
So my relevant `skin.conf` settings are like this - I've changed the `marker_type` setting, as with it as none, the values prior to installing neowx weren't visible!
  `# Type of line. Only 'solid' or 'none' is offered now`
    `line_type = 'solid'`
    `# Size of marker in pixels`
    `marker_size = 8`
    `# Type of marker. Pick one of 'cross', 'x', 'circle', 'box', or 'none'`
    `marker_type ='circle'`

I have made other modifications to the `skin.conf`, but only relate to setting the correct path for the fonts on my system.

My `weewx.conf` doesn't contain any graphics information.

I've attached both files, in case there's other information in them that proves useful.

Paddy

[Conf.zip](https://github.com/neoground/neowx/files/2719508/Conf.zip)

**Comment by MadderPad** [comment]
Actually just looking at this again in a browser, it's only the 'current' graphs that are affected - the weekly/monthly/yearly have all drawn correctly with lines going back to setup on weewx on my system.

So in the next hour or two, it will cease to be an issue for me :)

![daytempdew](https://user-images.githubusercontent.com/19325302/50575011-ddbae700-0deb-11e9-969f-20273e289b73.png)

**Comment by neoground** [comment]
Well this is very strange and I wasn't able to reproduce this on a testing environment. Anyways I guess this was some kind of weewx bug. But as long as your current graphs are now fine this shouldn't be a problem anymore.

By the way your date in your graph is very small on the bottom. You may need to adjust the font settings so it's as large as every other font in the graphs.
